services:
  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./back/postgre/data:/var/lib/postgresql/data